#!/usr/bin/env bash

set -eu

here="$(cd "$(dirname $0)" && pwd)"
source "$here/prelude.bash"
source "$here/command/create.bash"
source "$here/command/list.bash"
source "$here/command/info.bash"
source "$here/command/edit.bash"
source "$here/command/delete.bash"
source "$here/command/fire.bash"
source "$here/command/path.bash"


usage() {
    cat <<EOF
Usage: arbash COMMAND [OPTIONS]

Available options:
  --help
  --version

Available commands:
  create
  list
  info
  edit
  delete
  fire
  path

EOF
}

main()  {
    local command
    command="$(fetch_arg 0 COMMAND "")"
    case $command in
        "" )
            if [[ -n ${opts[version]+x} ]]; then
                echo "$VERSION"
            elif [[ -n ${opts[help]+x} ]]; then
                usage
            else
                usage
                exit 1
            fi
            ;;
        create|list|info|edit|delete|fire|path )
            if [[ -n ${opts[help]+x} ]]; then
                "command.${command}.usage"
            else
                "command.${command}.run"
            fi
            ;;
        * ) die "Unknown command: $command" ;;
    esac
}


root_dir="${ARBASH_ROOT:-$HOME/.arbash}"
templates_dir="${ARBASH_TEMPLATES_DIR:-$root_dir/templates}"

declare -a args
declare -A opts
parse_args "$@"
main
